### ISSUE TITLE
Dice loss calculation

### ISSUE THREAD

**Issue by ashkanaev** [chinakook/U-Net#2]
Hi, @chinakook !

Found  some strange multiplication in WeightedBCEDICE loss function.
https://github.com/chinakook/U-Net/blob/a02ae29070961a18811e906460d9d7fd5904deeb/train.py#L298
  What should be as result of multiplication of two index arrays? May be in this case label and pred should contains probability distributions?

**Comment by chinakook** [comment]
Both pred_y and label have only 0 or 1 values.

**Comment by ashkanaev** [comment]
@chinakook 
ohhh, ok it's only for binary task ) My bad
